# -*- coding: utf-8 -*-
"""Ablation Studies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UmcOJtGc8GppzXk7e3jlOhi_Vh7q8qVR

**SGBoost**
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from collections import defaultdict

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

# Store results
results = defaultdict(dict)

# Loop through each target column
for target in target_columns:
    y = df[target]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply PCA
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    # ========== Without SMOTE ==========
    model_no_smote = GradientBoostingClassifier(random_state=42)
    model_no_smote.fit(X_train_pca, y_train)
    y_pred_no_smote = model_no_smote.predict(X_test_pca)

    acc_no_smote = accuracy_score(y_test, y_pred_no_smote)
    prec_no_smote = precision_score(y_test, y_pred_no_smote)
    rec_no_smote = recall_score(y_test, y_pred_no_smote)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_no_smote).ravel()
    specificity_no_smote = tn / (tn + fp)

    results[target]['accuracy_without_smote'] = acc_no_smote
    results[target]['precision_without_smote'] = prec_no_smote
    results[target]['recall_without_smote'] = rec_no_smote
    results[target]['specificity_without_smote'] = specificity_no_smote

    # ========== With SMOTE ==========
    """
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_train_scaled, y_train)

    X_resampled_pca = pca.fit_transform(X_resampled)
    X_test_pca = pca.transform(X_test_scaled)  # Re-transform test set with PCA fitted on resampled data

    model_with_smote = GradientBoostingClassifier(random_state=42)
    model_with_smote.fit(X_resampled_pca, y_resampled)
    y_pred_smote = model_with_smote.predict(X_test_pca)

    acc_smote = accuracy_score(y_test, y_pred_smote)
    prec_smote = precision_score(y_test, y_pred_smote)
    rec_smote = recall_score(y_test, y_pred_smote)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_smote).ravel()
    specificity_smote = tn / (tn + fp)

    results[target]['accuracy_with_smote'] = acc_smote
    results[target]['precision_with_smote'] = prec_smote
    results[target]['recall_with_smote'] = rec_smote
    results[target]['specificity_with_smote'] = specificity_smote
    """
# Compile results into a DataFrame
results_df = pd.DataFrame(results).T
results_df.reset_index(inplace=True)
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)
#results_df = results_df.sort_values(by='specificity_with_smote', ascending=False)

# Display results
print(results_df.round(3))

"""XGBoost"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from collections import defaultdict

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

# Store results
results = defaultdict(dict)

# Loop through each target column
for target in target_columns:
    y = df[target]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply PCA
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    # ========== Without SMOTE ==========
    model_no_smote = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
    model_no_smote.fit(X_train_pca, y_train)
    y_pred_no_smote = model_no_smote.predict(X_test_pca)

    acc_no_smote = accuracy_score(y_test, y_pred_no_smote)
    prec_no_smote = precision_score(y_test, y_pred_no_smote)
    rec_no_smote = recall_score(y_test, y_pred_no_smote)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_no_smote).ravel()
    specificity_no_smote = tn / (tn + fp)

    results[target]['accuracy_without_smote'] = acc_no_smote
    results[target]['precision_without_smote'] = prec_no_smote
    results[target]['recall_without_smote'] = rec_no_smote
    results[target]['specificity_without_smote'] = specificity_no_smote



# Compile results into a DataFrame
results_df = pd.DataFrame(results).T
results_df.reset_index(inplace=True)
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

# Display results
print(results_df.round(3))

"""**Cost-Sensitive LightGBM**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from collections import defaultdict, Counter

# 1. Load the dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# 2. Separate features and targets (last 8 columns as faults)
num_targets = 8
X = df.iloc[:, :-num_targets]
target_columns = df.columns[-num_targets:]

# 3. Dictionary to hold results
results = defaultdict(dict)

# 4. Loop through each fault type
for target in target_columns:
    y = df[target]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply SMOTE
    smote = SMOTE(random_state=42)
    X_res, y_res = smote.fit_resample(X_train_scaled, y_train)

    # PCA
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_res)
    X_test_pca = pca.transform(X_test_scaled)

    # Class weights for cost-sensitive learning
    class_counts = Counter(y_res)
    total = sum(class_counts.values())
    class_weights = {cls: total / (len(class_counts) * count) for cls, count in class_counts.items()}
    sample_weights = np.array([class_weights[label] for label in y_res])

    # Train Cost-Sensitive LightGBM
    lgb_model = LGBMClassifier(random_state=42)
    lgb_model.fit(X_train_pca, y_res, sample_weight=sample_weights)

    # Prediction
    y_pred = lgb_model.predict(X_test_pca)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)

    # Store results
    results[target]['accuracy_with_cost_lgbm'] = acc
    results[target]['precision_with_cost_lgbm'] = prec
    results[target]['recall_with_cost_lgbm'] = rec
    results[target]['specificity_with_cost_lgbm'] = specificity

# Compile results into DataFrame
results_df = pd.DataFrame(results).T.reset_index()
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

# Display formatted results
print(results_df.round(3))

"""**Hybrid LightGBM**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import VotingClassifier
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
from collections import defaultdict

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

results = defaultdict(dict)

for target in target_columns:
    y = df[target]

    # Handle missing values if any
    X_filled = X.fillna(X.mean())

    # Scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_filled)

    # Train-test split (fixed random_state for reproducibility)
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.3, stratify=y, random_state=42
    )

    # LightGBM hyperparameter grid
    lgbm = lgb.LGBMClassifier()
    param_grid = {
        'num_leaves': [60, 100],
        'learning_rate': [0.01, 0.05],
        'n_estimators': [100, 200]
    }

    # Grid search for LightGBM
    grid_search = GridSearchCV(lgbm, param_grid, cv=5, n_jobs=-1, verbose=0)
    grid_search.fit(X_train, y_train)
    best_lgbm = grid_search.best_estimator_

    # Gaussian Naive Bayes
    gnb = GaussianNB()

    # Voting Classifier (Hybrid)
    voting_clf = VotingClassifier(
        estimators=[('lgbm', best_lgbm), ('gnb', gnb)],
        voting='hard'
    )

    # Train hybrid model
    voting_clf.fit(X_train, y_train)

    # Predict on test set
    y_pred = voting_clf.predict(X_test)

    # Metrics calculation
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)

    # Store results
    results[target]['accuracy'] = acc
    results[target]['precision'] = prec
    results[target]['recall'] = rec
    results[target]['specificity'] = specificity

# Convert results to DataFrame
results_df = pd.DataFrame(results).T.reset_index()
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

print(results_df.round(3))

pip install catboost imbalanced-learn

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from collections import defaultdict

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

# Store results
results = defaultdict(dict)

# Loop through each target column
for target in target_columns:
    y = df[target]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply PCA
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    # ========== Without SMOTE ==========
    model_no_smote = CatBoostClassifier(random_seed=42, verbose=0)
    model_no_smote.fit(X_train_pca, y_train)
    y_pred_no_smote = model_no_smote.predict(X_test_pca)

    acc_no_smote = accuracy_score(y_test, y_pred_no_smote)
    prec_no_smote = precision_score(y_test, y_pred_no_smote)
    rec_no_smote = recall_score(y_test, y_pred_no_smote)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred_no_smote).ravel()
    specificity_no_smote = tn / (tn + fp)

    results[target]['accuracy_without_smote'] = acc_no_smote
    results[target]['precision_without_smote'] = prec_no_smote
    results[target]['recall_without_smote'] = rec_no_smote
    results[target]['specificity_without_smote'] = specificity_no_smote



# Compile results into a DataFrame
results_df = pd.DataFrame(results).T
results_df.reset_index(inplace=True)
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

# Display results
print(results_df.round(3))

"""**NGBoost**"""

pip install ngboost

pip install --upgrade ngboost

pip install tensorflow tensorflow_decision_forests

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from collections import defaultdict
from ngboost import NGBClassifier
from ngboost.scores import LogScore

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (last 8 columns = fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]
target_columns = df.columns[-num_targets:]

# Store results
results = defaultdict(dict)

# Loop through each target column (binary classification)
for target in target_columns:
    y = df[target]

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Feature Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply PCA
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)

    # Train NGBoost
    model = NGBClassifier(Score=LogScore, verbose=False)
    model.fit(X_train_pca, y_train)
    y_pred = model.predict(X_test_pca)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)

    # Confusion matrix and specificity
    try:
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred, labels=[0, 1]).ravel()
        specificity = tn / (tn + fp) if (tn + fp) else 0
    except:
        specificity = 0  # Handle edge cases with only one class in test set

    results[target]['accuracy_without_smote'] = acc
    results[target]['precision_without_smote'] = prec
    results[target]['recall_without_smote'] = rec
    results[target]['specificity_without_smote'] = specificity

# Compile results into DataFrame
results_df = pd.DataFrame(results).T
results_df.reset_index(inplace=True)
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

# Show results
print(results_df.round(3))

"""**TFXGBT**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import tensorflow as tf
import tensorflow_decision_forests as tfdf
import matplotlib.pyplot as plt
import seaborn as sns
from collections import defaultdict

# 1. Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# 2. Define features and targets (last 8 columns assumed faults)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns

# Store results for each fault type
results = defaultdict(dict)

for target in target_columns:
    print(f"\nTraining for fault: {target}")

    y = df[target]

    # 3. Train-test split with stratification
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # 4. Scaling features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # 5. SMOTE to balance classes in training data
    smote = SMOTE(random_state=42)
    X_res, y_res = smote.fit_resample(X_train_scaled, y_train)

    # 6. PCA for dimensionality reduction (retain 95% variance)
    pca = PCA(n_components=0.95, random_state=42)
    X_train_pca = pca.fit_transform(X_res)
    X_test_pca = pca.transform(X_test_scaled)

    # 7. Prepare DataFrame for TFDF - convert labels to strings for classification
    train_df = pd.DataFrame(X_train_pca)
    train_df['label'] = y_res.astype(str).values  # Convert labels to string

    test_df = pd.DataFrame(X_test_pca)
    test_df['label'] = y_test.astype(str).values  # Convert labels to string

    # 8. Convert pandas DataFrame to TensorFlow dataset
    train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(train_df, label='label')
    test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(test_df, label='label')

    # 9. Initialize and train TFDF Gradient Boosted Trees model
    model = tfdf.keras.GradientBoostedTreesModel(verbose=0)
    model.fit(train_ds)

    # 10. Predict on test set
    predictions = model.predict(test_ds)

    # TFDF returns predictions as a numpy array of shape (num_samples, num_classes)
    # Get predicted class index (argmax) for multiclass or binary classification
    if predictions.shape[1] > 1:
        y_pred_indices = np.argmax(predictions, axis=1)
        # Map indices back to label strings from the model
        class_labels = model.classes_
        y_pred = [class_labels[i] for i in y_pred_indices]
    else:
        # For binary classification, predictions shape might be (num_samples, 1)
        y_pred = (predictions.flatten() > 0.5).astype(int).astype(str)

    # 11. Convert true labels to string for consistency
    y_test_str = y_test.astype(str).values

    # 12. Calculate evaluation metrics
    acc = accuracy_score(y_test_str, y_pred)
    prec = precision_score(y_test_str, y_pred, pos_label='1', zero_division=0)
    rec = recall_score(y_test_str, y_pred, pos_label='1', zero_division=0)

    # Confusion matrix for binary classification (assuming labels '0' and '1')
    cm = confusion_matrix(y_test_str, y_pred, labels=['0', '1'])
    tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0,0,0,0)
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    # Save results
    results[target]['accuracy'] = acc
    results[target]['precision'] = prec
    results[target]['recall'] = rec
    results[target]['specificity'] = specificity

    # 13. Print classification report
    print(f"Accuracy: {acc:.3f}")
    print(f"Precision: {prec:.3f}")
    print(f"Recall: {rec:.3f}")
    print(f"Specificity: {specificity:.3f}")
    print("Classification Report:\n", classification_report(y_test_str, y_pred, zero_division=0))

    # 14. Plot confusion matrix
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['No Fault', 'Fault'], yticklabels=['No Fault', 'Fault'])
    plt.title(f'Confusion Matrix for {target}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.show()

# 15. Compile results in a DataFrame and display
results_df = pd.DataFrame(results).T.reset_index().rename(columns={'index': 'Fault_Type'})
print("\nSummary of results for all faults:")
print(results_df.round(3))

"""**GBDT++**"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import GradientBoostingClassifier, VotingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from scipy.stats import randint, uniform
from collections import defaultdict

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

results = defaultdict(dict)

for target in target_columns:
    print(f"Training for fault: {target}")

    y = df[target]

    # Handle missing values if any
    X_filled = X.fillna(X.mean())

    # Scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_filled)

    # Train-test split (fixed random_state for reproducibility)
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.3, stratify=y, random_state=42
    )

    # Hyperparameter distribution for GBDT
    param_dist = {
        'n_estimators': randint(100, 500),
        'learning_rate': uniform(0.01, 0.2),
        'max_depth': randint(3, 10),
        'min_samples_split': randint(2, 10),
        'min_samples_leaf': randint(1, 10),
        'subsample': uniform(0.6, 0.4)
    }

    gbdt = GradientBoostingClassifier(random_state=42)

    # Randomized search for GBDT++
    random_search = RandomizedSearchCV(
        gbdt, param_distributions=param_dist,
        n_iter=30, cv=3, scoring='accuracy',
        random_state=42, n_jobs=-1, verbose=1
    )

    # Fit randomized search
    random_search.fit(X_train, y_train)
    best_gbdt = random_search.best_estimator_

    # Gaussian Naive Bayes
    gnb = GaussianNB()

    # Voting Classifier (GBDT++ + GNB)
    voting_clf = VotingClassifier(
        estimators=[('gbdt', best_gbdt), ('gnb', gnb)],
        voting='hard'
    )

    # Train the hybrid model
    voting_clf.fit(X_train, y_train)

    # Predict on test set
    y_pred = voting_clf.predict(X_test)

    # Calculate metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    # Store results
    results[target]['accuracy'] = acc
    results[target]['precision'] = prec
    results[target]['recall'] = rec
    results[target]['specificity'] = specificity

# Convert results to DataFrame
results_df = pd.DataFrame(results).T.reset_index()
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

print("\nSummary of results:")
print(results_df.round(3))

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# 2. Feature & target separation
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# 3. Train-test split (70:30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 4. Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

##############################
# 🚫 WITHOUT SMOTE
##############################

# 5. PCA
pca = PCA(n_components=0.95, random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# 6. Train SGBoost
sgboost_model = GradientBoostingClassifier(random_state=42)
sgboost_model.fit(X_train_pca, y_train)

# 7. Predict
y_pred = sgboost_model.predict(X_test_pca)

# 8. Evaluation
print("✅ SGBoost Evaluation WITHOUT SMOTE:")
accuracy_without_smote = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy_without_smote * 100, '%')
print("Classification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=['No', 'Gas Leakage'], yticklabels=['No', 'Gas Leakage'])
plt.title('SGBoost WITHOUT SMOTE (for Gas Leakage)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Save report
report_without_smote = classification_report(y_test, y_pred, output_dict=True)

##############################
# ✅ WITH SMOTE
##############################

# 9. Apply SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train_scaled, y_train)

# 10. PCA
pca_smote = PCA(n_components=0.95, random_state=42)
X_train_pca_smote = pca_smote.fit_transform(X_res)
X_test_pca_smote = pca_smote.transform(X_test_scaled)

# 11. Train SGBoost
sgboost_model_smote = GradientBoostingClassifier(random_state=42)
sgboost_model_smote.fit(X_train_pca_smote, y_res)

# 12. Predict
y_pred_smote = sgboost_model_smote.predict(X_test_pca_smote)

# 13. Evaluation
print("\n✅ SGBoost Evaluation WITH SMOTE:")
accuracy_with_smote = accuracy_score(y_test, y_pred_smote)
print("Accuracy:", accuracy_with_smote * 100, '%')
print("Classification Report:\n", classification_report(y_test, y_pred_smote))

# Confusion Matrix
cm_smote = confusion_matrix(y_test, y_pred_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_smote, annot=True, fmt='d', cmap='Greens', cbar=True,
            xticklabels=['No', 'Gas Leakage'], yticklabels=['No', 'Gas Leakage'])
plt.title('SGBoost WITH SMOTE (for Gas Leakage)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Save report
report_with_smote = classification_report(y_test, y_pred_smote, output_dict=True)

##############################
# 📊 COMPARISON
##############################

minority_class = list(report_without_smote.keys())[1]  # Assuming class '1' is minority (e.g., Gas Leakage)
recall_without = report_without_smote[minority_class]['recall']
precision_without = report_without_smote[minority_class]['precision']
f1_without = report_without_smote[minority_class]['f1-score']

recall_with = report_with_smote[minority_class]['recall']
precision_with = report_with_smote[minority_class]['precision']
f1_with = report_with_smote[minority_class]['f1-score']

print("\n📉 Performance Comparison Summary:")
print(f"Accuracy WITHOUT SMOTE: {accuracy_without_smote*100:.2f}%")
print(f"Accuracy WITH SMOTE:    {accuracy_with_smote*100:.2f}%")

print(f"\n🎯 Minority Class '{minority_class}' Metrics:")
print(f"Recall    WITHOUT SMOTE: {recall_without:.2f} | WITH SMOTE: {recall_with:.2f}")
print(f"Precision WITHOUT SMOTE: {precision_without:.2f} | WITH SMOTE: {precision_with:.2f}")
print(f"F1-Score  WITHOUT SMOTE: {f1_without:.2f} | WITH SMOTE: {f1_with:.2f}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.decomposition import PCA
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# 2. Feature & target separation
X = df.iloc[:, :-8]
y = df.iloc[:, -8]

# 3. Train-test split (70:30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# 4. Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

##############################
# 🚫 WITHOUT SMOTE
##############################

# 5. PCA
pca = PCA(n_components=0.95, random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# 6. Train SGBoost
sgboost_model = GradientBoostingClassifier(random_state=42)
sgboost_model.fit(X_train_pca, y_train)

# 7. Predict
y_pred = sgboost_model.predict(X_test_pca)

# 8. Evaluation
print("✅ SGBoost Evaluation WITHOUT SMOTE:")
accuracy_without_smote = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy_without_smote * 100, '%')
print("Classification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=True,
            xticklabels=['No', 'Gas Leakage'], yticklabels=['No', 'Gas Leakage'])
plt.title('SGBoost WITHOUT SMOTE (for Gas Leakage)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Save report
report_without_smote = classification_report(y_test, y_pred, output_dict=True)

##############################
# ✅ WITH SMOTE
##############################

# 9. Apply SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train_scaled, y_train)

# 10. PCA
pca_smote = PCA(n_components=0.95, random_state=42)
X_train_pca_smote = pca_smote.fit_transform(X_res)
X_test_pca_smote = pca_smote.transform(X_test_scaled)

# 11. Train SGBoost
sgboost_model_smote = GradientBoostingClassifier(random_state=42)
sgboost_model_smote.fit(X_train_pca_smote, y_res)

# 12. Predict
y_pred_smote = sgboost_model_smote.predict(X_test_pca_smote)

# 13. Evaluation
print("\n✅ SGBoost Evaluation WITH SMOTE:")
accuracy_with_smote = accuracy_score(y_test, y_pred_smote)
print("Accuracy:", accuracy_with_smote * 100, '%')
print("Classification Report:\n", classification_report(y_test, y_pred_smote))

# Confusion Matrix
cm_smote = confusion_matrix(y_test, y_pred_smote)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_smote, annot=True, fmt='d', cmap='Greens', cbar=True,
            xticklabels=['No', 'Gas Leakage'], yticklabels=['No', 'Gas Leakage'])
plt.title('SGBoost WITH SMOTE (for Gas Leakage)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()

# Save report
report_with_smote = classification_report(y_test, y_pred_smote, output_dict=True)

##############################
# 📊 COMPARISON
##############################

minority_class = list(report_without_smote.keys())[1]  # Assuming class '1' is minority (e.g., Gas Leakage)
recall_without = report_without_smote[minority_class]['recall']
precision_without = report_without_smote[minority_class]['precision']
f1_without = report_without_smote[minority_class]['f1-score']

recall_with = report_with_smote[minority_class]['recall']
precision_with = report_with_smote[minority_class]['precision']
f1_with = report_with_smote[minority_class]['f1-score']

print("\n📉 Performance Comparison Summary:")
print(f"Accuracy WITHOUT SMOTE: {accuracy_without_smote*100:.2f}%")
print(f"Accuracy WITH SMOTE:    {accuracy_with_smote*100:.2f}%")

print(f"\n🎯 Minority Class '{minority_class}' Metrics:")
print(f"Recall    WITHOUT SMOTE: {recall_without:.2f} | WITH SMOTE: {recall_with:.2f}")
print(f"Precision WITHOUT SMOTE: {precision_without:.2f} | WITH SMOTE: {precision_with:.2f}")
print(f"F1-Score  WITHOUT SMOTE: {f1_without:.2f} | WITH SMOTE: {f1_with:.2f}")

import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load your dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Feature & target separation
X = df.iloc[:, :-2]
y = df.iloc[:, -2]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42
)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

# 1️⃣ Before SMOTE
print("Class distribution BEFORE SMOTE:", Counter(y_train))
plt.figure(figsize=(5, 4))
plt.title("Before SMOTE")
plt.bar(Counter(y_train).keys(), Counter(y_train).values(), color='tomato')
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.show()

# 2️⃣ Apply SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_scaled, y_train)

# 3️⃣ After SMOTE
print("Class distribution AFTER SMOTE:", Counter(y_resampled))
plt.figure(figsize=(5, 4))
plt.title("After SMOTE")
plt.bar(Counter(y_resampled).keys(), Counter(y_resampled).values(), color='skyblue')
plt.xlabel("Class")
plt.ylabel("Number of Samples")
plt.show()

# 4️⃣ Additional Statistics
print("Shape before SMOTE:", X_train_scaled.shape)
print("Shape after SMOTE: ", X_resampled.shape)
print("\nNumber of synthetic samples added:",
      X_resampled.shape[0] - X_train_scaled.shape[0])

import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

# Loop through each target column
for target in target_columns:
    print(f"\n{'='*20} Processing Fault: {target} {'='*20}")

    y = df[target]  # Single fault column as target

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    # 1️⃣ Before SMOTE
    print("Class distribution BEFORE SMOTE:", Counter(y_train))
    plt.figure(figsize=(4, 3))
    plt.title(f"Before SMOTE - {target}")
    plt.bar(Counter(y_train).keys(), Counter(y_train).values(), color='tomato')
    plt.xlabel("Class")
    plt.ylabel("Samples")
    plt.tight_layout()
    plt.show()

    # 2️⃣ Apply SMOTE
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_train_scaled, y_train)

    # 3️⃣ After SMOTE
    print("Class distribution AFTER SMOTE:", Counter(y_resampled))
    plt.figure(figsize=(4, 3))
    plt.title(f"After SMOTE - {target}")
    plt.bar(Counter(y_resampled).keys(), Counter(y_resampled).values(), color='skyblue')
    plt.xlabel("Class")
    plt.ylabel("Samples")
    plt.tight_layout()
    plt.show()

    # 4️⃣ Additional Statistics
    print("Shape before SMOTE:", X_train_scaled.shape)
    print("Shape after SMOTE: ", X_resampled.shape)
    print("Synthetic samples added:",
          X_resampled.shape[0] - X_train_scaled.shape[0])

import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets (assuming last 8 columns are fault types)
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

# Loop through each target column
for target in target_columns:
    print(f"\n{'='*25} Fault Type: {target} {'='*25}")

    y = df[target]  # Target fault column

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=42
    )

    # Scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    # Record class distribution before SMOTE
    counter_before = Counter(y_train)

    # Apply SMOTE
    smote = SMOTE(random_state=42)
    X_resampled, y_resampled = smote.fit_resample(X_train_scaled, y_train)

    # Record class distribution after SMOTE
    counter_after = Counter(y_resampled)

    # Print stats
    print("Class distribution BEFORE SMOTE:", counter_before)
    print("Class distribution AFTER SMOTE :", counter_after)
    print("Shape before SMOTE:", X_train_scaled.shape)
    print("Shape after SMOTE: ", X_resampled.shape)
    print("Synthetic samples added:",
          X_resampled.shape[0] - X_train_scaled.shape[0])

    # Side-by-side bar plot
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].bar(counter_before.keys(), counter_before.values(), color='green')
    axes[0].set_title(f"Before SMOTE - {target}")
    axes[0].set_xlabel("Class")
    axes[0].set_ylabel("Samples")

    axes[1].bar(counter_after.keys(), counter_after.values(), color='purple')
    axes[1].set_title(f"After SMOTE - {target}")
    axes[1].set_xlabel("Class")
    axes[1].set_ylabel("Samples")

    plt.tight_layout()
    plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from collections import defaultdict
import tensorflow_decision_forests as tfdf
import tensorflow as tf

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Define number of last columns used as targets
num_targets = 8
X = df.iloc[:, :-num_targets]  # Features
target_columns = df.columns[-num_targets:]  # Last 8 columns as target names

results = defaultdict(dict)

for target in target_columns:
    print(f"\nTraining for fault: {target}")
    y = df[target]

    # Handle missing values
    X_filled = X.fillna(X.mean())

    # Scaling
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_filled)

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.3, stratify=y, random_state=42
    )

    # 1. Extra Trees
    et_model = ExtraTreesClassifier(n_estimators=100, random_state=42)
    et_model.fit(X_train, y_train)
    et_preds = et_model.predict(X_test)

    # 2. Gradient Boosting
    gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
    gb_model.fit(X_train, y_train)
    gb_preds = gb_model.predict(X_test)

    # 3. TFDF Model (Gradient Boosted Trees)
    # Convert to DataFrame for TFDF
    X_train_df = pd.DataFrame(X_train, columns=[f'F{i}' for i in range(X_train.shape[1])])
    X_train_df['label'] = y_train.values

    X_test_df = pd.DataFrame(X_test, columns=[f'F{i}' for i in range(X_test.shape[1])])
    X_test_df['label'] = y_test.values

    train_ds = tfdf.keras.pd_dataframe_to_tf_dataset(X_train_df, label="label")
    test_ds = tfdf.keras.pd_dataframe_to_tf_dataset(X_test_df, label="label")

    tf_model = tfdf.keras.GradientBoostedTreesModel()
    tf_model.fit(train_ds, verbose=0)

    tf_preds_prob = tf_model.predict(test_ds)
    tf_preds = np.argmax(tf_preds_prob, axis=1)  # Binary: assumes labels [0,1]

    # 4. Voting: Majority vote (binary case)
    # Ensure all predictions are integer numpy arrays
    ensemble_preds = ((et_preds + gb_preds + tf_preds) > 1).astype(int)

    # 5. Evaluation
    acc = accuracy_score(y_test, ensemble_preds)
    prec = precision_score(y_test, ensemble_preds, zero_division=0)
    rec = recall_score(y_test, ensemble_preds, zero_division=0)
    tn, fp, fn, tp = confusion_matrix(y_test, ensemble_preds).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0

    # Store results
    results[target]['accuracy'] = acc
    results[target]['precision'] = prec
    results[target]['recall'] = rec
    results[target]['specificity'] = specificity

# Convert to DataFrame
results_df = pd.DataFrame(results).T.reset_index()
results_df.rename(columns={'index': 'Fault_Type'}, inplace=True)

print("\nSummary of TFXGBT Results (without SMOTE):")
print(results_df.round(3))

