# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGtI35XkwNFN9Ru2qVvcZ8AJBXIaDXiB
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("/content/Vibration_Dataset.csv")

# Drop the target/fault columns (non-numeric or categorical columns)
sensor_features = df.drop(columns=[
    'Wiring Reversal', 'Offset Bias', 'Sensor Aging (Degradation)',
    'Thermal Drift', 'Radiation-Induced Degradation',
    'High Noise Levels', 'Gas Leakage', 'Signal Drift'
])

# Standardize the features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(sensor_features)

# Apply PCA
pca = PCA()
pca_result = pca.fit_transform(scaled_data)

# Explained variance
explained_variance = pca.explained_variance_ratio_
cumulative_variance = explained_variance.cumsum()

# Plotting
plt.figure(figsize=(20, 8))

# Explained variance bar plot
plt.subplot(1, 2, 1)
sns.barplot(x=list(range(1, len(explained_variance) + 1)), y=explained_variance, color="blue")
plt.title('Explained Variance by Each Principal Component')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')

# Cumulative variance line plot
plt.subplot(1, 2, 2)
sns.lineplot(x=list(range(1, len(cumulative_variance) + 1)), y=cumulative_variance, marker="o", color="green")
plt.title('Cumulative Explained Variance')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance Ratio')

plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load dataset (already uploaded earlier)
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Drop non-numeric columns if needed (e.g., labels or IDs)
numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Standardize the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

# Apply PCA
pca = PCA()
pca_data = pca.fit_transform(scaled_data)

# Create a DataFrame for PC values
pc_df = pd.DataFrame(pca_data, columns=[f'PC{i+1}' for i in range(pca_data.shape[1])])

# View first few rows of PC values
print(pc_df.head())

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd

# Load dataset
df = pd.read_csv('/content/Vibration_Dataset.csv')

# Select only numeric columns
numeric_df = df.select_dtypes(include=['float64', 'int64'])

# Standardize the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(numeric_df)

# Apply PCA with variance threshold
pca = PCA(n_components=0.95)  # Keep enough PCs to explain 95% variance
pca_data = pca.fit_transform(scaled_data)

# Create DataFrame for retained PC values
pc_df = pd.DataFrame(pca_data, columns=[f'PC{i+1}' for i in range(pca_data.shape[1])])

# Output: number of PCs retained and first few rows
print(f"Number of PCs retained: {pca_data.shape[1]}")
print(pc_df.head())

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("/content/Vibration_Dataset.csv")

# Drop the target/fault columns (non-numeric or categorical columns)
sensor_features = df.drop(columns=[
    'Wiring Reversal', 'Offset Bias', 'Sensor Aging (Degradation)',
    'Thermal Drift', 'Radiation-Induced Degradation',
    'High Noise Levels', 'Gas Leakage', 'Signal Drift'
])

# Standardize the features
scaler = StandardScaler()
scaled_data = scaler.fit_transform(sensor_features)

# Apply PCA to retain components explaining 95% variance
pca = PCA(n_components=0.95)
pca_result = pca.fit_transform(scaled_data)

# Explained variance (only for retained components)
explained_variance = pca.explained_variance_ratio_
cumulative_variance = explained_variance.cumsum()

# Plotting
plt.figure(figsize=(12, 6))

# Explained variance bar plot
plt.subplot(1, 2, 1)
sns.barplot(x=list(range(1, len(explained_variance) + 1)), y=explained_variance, color="orange")
plt.title('Explained Variance by Retained Principal Components')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')

# Cumulative variance line plot
plt.subplot(1, 2, 2)
sns.lineplot(x=list(range(1, len(cumulative_variance) + 1)), y=cumulative_variance, marker="o", color="green")
plt.title('Cumulative Explained Variance (≥95%)')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance Ratio')

plt.tight_layout()
plt.show()

# Optional: print number of components retained
print(f"Number of Principal Components retained (≥95% variance): {pca.n_components_}")

